sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=default-debian-8
    - INSTANCE=default-debian-9
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-fedora-latest
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml travis_wait 100 /opt/chefdk/embedded/bin/kitchen converge ${INSTANCE}
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1
  # Unfortunately CentOS 6 + JRuby seems to have some issue with Read timeouts in Docker. Normally
  # this is really bad to allow_failures, but honestly these tests dont vary much per OS, and CentOS
  # 7 is still covered. https://github.com/sous-chefs/ruby_build/issues/64
  allow_failures:
    - env: INSTANCE=default-centos-6
  fast_finish: true
